PROMPT LOG TO SML-1.0.0.log
PROMPT .
SET AUTOCOMMIT OFF
SET AUTOPRINT ON
SET ECHO ON
SET FEEDBACK ON
SET PAUSE OFF
SET SERVEROUTPUT ON SIZE 1000000
SET TERMOUT ON
SET TRIMOUT ON
SET VERIFY ON
SET trims on pagesize 3000
SET auto off
SET verify off echo off define on
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

SPOOL SML-1.0.0.log
Prompt installing PATCHES
spool off;

SPOOL SML-1.0.0.log APPEND
PROMPT feature\SDEPLOY-41\SDEPLOY-41.01.LOGGER 
spool off;
@feature\SDEPLOY-41\SDEPLOY-41.01.LOGGER\install_lite.sql;
SPOOL SML-1.0.0.log APPEND
PROMPT feature\QHIDS-2650\QHIDS-2650.01.APEXRM 
spool off;
@feature\QHIDS-2650\QHIDS-2650.01.APEXRM\install_lite.sql;
SPOOL SML-1.0.0.log APPEND
PROMPT feature\SML-001\SML-001.01.LOGGER 
spool off;
@feature\SML-001\SML-001.01.LOGGER\install_lite.sql;
SPOOL SML-1.0.0.log APPEND
PROMPT 
PROMPT install_lite.sql - COMPLETED.
spool off;
