prompt --application/pages/page_00001
begin
wwv_flow_api.create_page(
 p_id=>1
,p_user_interface_id=>wwv_flow_api.id(37981134484256182)
,p_name=>'Dashboard'
,p_step_title=>'Dashboard'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_step_sub_title=>'Page 1'
,p_step_sub_title_type=>'TEXT_WITH_SUBSTITUTIONS'
,p_first_item=>'AUTO_FIRST_ITEM'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'PETER'
,p_last_upd_yyyymmddhh24miss=>'20180930023827'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(35941505421734638)
,p_plug_name=>'Activity by Module'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(35560371291315922)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY_3'
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(35941581623734639)
,p_region_id=>wwv_flow_api.id(35941505421734638)
,p_chart_type=>'bar'
,p_animation_on_display=>'none'
,p_animation_on_data_change=>'none'
,p_orientation=>'vertical'
,p_data_cursor=>'auto'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'none'
,p_hover_behavior=>'none'
,p_stack=>'on'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_show_label=>true
,p_legend_rendered=>'on'
,p_legend_position=>'auto'
,p_overview_rendered=>'off'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35941701466734640)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_seq=>10
,p_name=>'Comment'
,p_data_source_type=>'SQL'
,p_data_source=>'select null, module_name, comment_count from sm_module_vw order by module_name'
,p_items_value_column_name=>'COMMENT_COUNT'
,p_items_label_column_name=>'MODULE_NAME'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35941981927734643)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_seq=>20
,p_name=>'Info'
,p_data_source_type=>'SQL'
,p_data_source=>'select null, module_name, info_count from sm_module_vw order by module_name'
,p_items_value_column_name=>'INFO_COUNT'
,p_items_label_column_name=>'MODULE_NAME'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35942119174734644)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_seq=>30
,p_name=>'Warning'
,p_data_source_type=>'SQL'
,p_data_source=>'select null, module_name, warning_count from sm_module_vw order by module_name'
,p_items_value_column_name=>'WARNING_COUNT'
,p_items_label_column_name=>'MODULE_NAME'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35942171960734645)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_seq=>40
,p_name=>'Fatal'
,p_data_source_type=>'SQL'
,p_data_source=>'select null, module_name, fatal_count from sm_module_vw order by module_name'
,p_items_value_column_name=>'FATAL_COUNT'
,p_items_label_column_name=>'MODULE_NAME'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35942278155734646)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_seq=>50
,p_name=>'Oracle Error'
,p_data_source_type=>'SQL'
,p_data_source=>'select null, module_name, oracle_count from sm_module_vw order by module_name'
,p_items_value_column_name=>'ORACLE_COUNT'
,p_items_label_column_name=>'MODULE_NAME'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(35941864533734642)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Messages'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(35941819598734641)
,p_chart_id=>wwv_flow_api.id(35941581623734639)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Modules'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(35942392748734647)
,p_plug_name=>'Activity by Date'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(35560371291315922)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY_3'
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(35942514147734648)
,p_region_id=>wwv_flow_api.id(35942392748734647)
,p_chart_type=>'lineWithArea'
,p_animation_on_display=>'none'
,p_animation_on_data_change=>'none'
,p_orientation=>'vertical'
,p_data_cursor=>'auto'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'none'
,p_hover_behavior=>'none'
,p_stack=>'off'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_show_label=>true
,p_legend_rendered=>'on'
,p_legend_position=>'auto'
,p_overview_rendered=>'off'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(35942650294734649)
,p_chart_id=>wwv_flow_api.id(35942514147734648)
,p_seq=>10
,p_name=>'Session'
,p_data_source_type=>'SQL'
,p_data_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select null',
'     , to_char(trunc(created_date),''DD-MON-YYYY'') session_date',
'     , count(*) session_count ',
'from sm_session',
'group by trunc(created_date) ',
'order by trunc(created_date) '))
,p_items_value_column_name=>'SESSION_COUNT'
,p_items_label_column_name=>'SESSION_DATE'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'on'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(28077825637555226)
,p_chart_id=>wwv_flow_api.id(35942514147734648)
,p_seq=>20
,p_name=>'Messages'
,p_data_source_type=>'SQL'
,p_data_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select null',
'     , to_char(trunc(created_date),''DD-MON-YYYY'') session_date',
'     , sum(message_count) message_count',
'from sm_session_v2',
'group by trunc(created_date) ',
'order by trunc(created_date) '))
,p_items_value_column_name=>'MESSAGE_COUNT'
,p_items_label_column_name=>'SESSION_DATE'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(28077938607555227)
,p_chart_id=>wwv_flow_api.id(35942514147734648)
,p_axis=>'y2'
,p_is_rendered=>'on'
,p_title=>'Sessions'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_split_dual_y=>'auto'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(35942691816734650)
,p_chart_id=>wwv_flow_api.id(35942514147734648)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Activity Dates'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(35942841316734651)
,p_chart_id=>wwv_flow_api.id(35942514147734648)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Messages'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(53231866369577623)
,p_plug_name=>'Dashboard'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(35559327458315922)
,p_plug_display_sequence=>10
,p_plug_display_point=>'BODY_3'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
,p_attribute_03=>'N'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(53232052458577625)
,p_plug_name=>'Breadcrumbs'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(35569579936315926)
,p_plug_display_sequence=>1
,p_plug_display_point=>'REGION_POSITION_01'
,p_plug_item_display_point=>'BELOW'
,p_menu_id=>wwv_flow_api.id(53231447489577620)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_api.id(35606742937315953)
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(28153781527113935)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(35942392748734647)
,p_button_name=>'PURGE_OLD'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--warning'
,p_button_template_id=>wwv_flow_api.id(35605892992315953)
,p_button_image_alt=>'Purge Old Sessions'
,p_button_position=>'REGION_TEMPLATE_EDIT'
,p_grid_new_grid=>false
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(28154004937115172)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(35942392748734647)
,p_button_name=>'PURGE_ALL'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--danger'
,p_button_template_id=>wwv_flow_api.id(35605892992315953)
,p_button_image_alt=>'Purge All Sessions'
,p_button_position=>'REGION_TEMPLATE_EDIT'
,p_grid_new_grid=>false
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(28154225877116869)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PurgeOldSessions'
,p_process_sql_clob=>'sm_api.purge_old_sessions;'
,p_process_when_button_id=>wwv_flow_api.id(28153781527113935)
,p_process_success_message=>'Purged old messages'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(28154546112118267)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PurgeAllSessions'
,p_process_sql_clob=>'sm_api.purge_old_sessions(i_keep_day_count => 0);'
,p_process_when_button_id=>wwv_flow_api.id(28154004937115172)
,p_process_success_message=>'Purged all messages'
);
end;
/
